# Generated by Django 6.1.1 on 2026-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('PHARMACIST', 'Pharmacist'), ('PHARMACY', 'Pharmacy'), ('DELIVERY', 'Delivery'), ('ADMIN', 'Admin')], db_index=True, default='CUSTOMER', max_length=20),
        ),
    ]
